package digital.singularidade.databridge.pipeline.ddl;

import digital.singularidade.databridge.BuildInfo;

import java.time.Instant;
import java.util.List;

/**
 * Result of DDL extraction for one table. Two output streams: the main DDL ({@code ddl.sql}) and
 * triggers ({@code triggers.sql}, only populated when {@code includeTriggers=true}).
 *
 * <p>{@link #toFileText()} adds a standard provenance header on top of the body.
 *
 * @param header human-readable provenance comment block (one '-- ' per line)
 * @param body   the actual SQL statements; one or more, separated by blank lines + trailing semicolons
 * @param triggers separate body for triggers (empty when {@code --include-triggers} not set)
 * @param warnings free-form notes about partial coverage (e.g. "RLS policies not extracted")
 */
public record DdlScript(String header, String body, String triggers, List<String> warnings) {

    public String toFileText() { return header + "\n\n" + body + "\n"; }

    public String triggersFileText() {
        return triggers == null || triggers.isBlank() ? "" : header + "\n\n" + triggers + "\n";
    }

    public static String standardHeader(String driver, String schema, String table,
                                         String redactedUrl, String serverBanner,
                                         List<String> includedSections, List<String> skippedSections) {
        StringBuilder h = new StringBuilder();
        h.append("-- Generated by ").append(BuildInfo.NAME).append(' ').append(BuildInfo.VERSION).append('\n');
        h.append("--   source:    ").append(redactedUrl == null ? "[unknown]" : redactedUrl).append('\n');
        h.append("--   server:    ").append(serverBanner == null ? "[unknown]" : serverBanner).append('\n');
        if (schema != null) h.append("--   schema:    ").append(schema).append("   table: ").append(table)
            .append("   driver: ").append(driver).append('\n');
        else h.append("--   table:     ").append(table).append("   driver: ").append(driver).append('\n');
        h.append("--   timestamp: ").append(Instant.now()).append('\n');
        if (!includedSections.isEmpty()) h.append("-- Included: ").append(String.join(", ", includedSections)).append('\n');
        if (!skippedSections.isEmpty()) h.append("-- Skipped:  ").append(String.join(", ", skippedSections)).append('\n');
        return h.toString().stripTrailing();
    }
}
